
LIST @BLUESKYDATAENGINEERINGPROJECT.PUBLIC.BLUESKY_ACTOR_PROFILES_STAGE;
LIST @BLUESKYDATAENGINEERINGPROJECT.PUBLIC.BLUESKY_RAW_POSTS_STAGE;
LIST @BLUESKYDATAENGINEERINGPROJECT.PUBLIC.BLUESKY_HYDRATED_POSTS_STAGE;

select * from @BLUESKYDATAENGINEERINGPROJECT.PUBLIC.BLUESKY_ACTOR_PROFILES_STAGE;

select * from BLUESKYDATAENGINEERINGPROJECT.PUBLIC.LANDING_RAW_POSTS;


ALTER STAGE BLUESKYDATAENGINEERINGPROJECT.PUBLIC.BLUESKY_RAW_POSTS_STAGE
  SET DIRECTORY = (ENABLE = TRUE);

ALTER STAGE BLUESKYDATAENGINEERINGPROJECT.PUBLIC.BLUESKY_RAW_POSTS_STAGE REFRESH;

ALTER STAGE BLUESKYDATAENGINEERINGPROJECT.PUBLIC.BLUESKY_HYDRATED_POSTS_STAGE
  SET DIRECTORY = (ENABLE = TRUE);

ALTER STAGE BLUESKYDATAENGINEERINGPROJECT.PUBLIC.BLUESKY_HYDRATED_POSTS_STAGE REFRESH;

ALTER STAGE BLUESKYDATAENGINEERINGPROJECT.PUBLIC.BLUESKY_ACTOR_PROFILES_STAGE
  SET DIRECTORY = (ENABLE = TRUE);

ALTER STAGE BLUESKYDATAENGINEERINGPROJECT.PUBLIC.BLUESKY_ACTOR_PROFILES_STAGE REFRESH;