
LIST @BLUESKYDATAENGINEERINGPROJECT.PUBLIC.BLUESKY_ACTOR_PROFILES_STAGE;
LIST @BLUESKYDATAENGINEERINGPROJECT.PUBLIC.BLUESKY_RAW_POSTS_STAGE;
LIST @BLUESKYDATAENGINEERINGPROJECT.PUBLIC.BLUESKY_HYDRATED_POSTS_STAGE;

select * from @BLUESKYDATAENGINEERINGPROJECT.PUBLIC.BLUESKY_ACTOR_PROFILES_STAGE;

select * from BLUESKYDATAENGINEERINGPROJECT.PUBLIC.LANDING_RAW_POSTS;

DROP TASK IF EXISTS ENHANCED.TASK_BUILD_ML_READY;
DROP TASK IF EXISTS ENHANCED.TASK_ENRICH_POSTS;
ALTER STAGE BLUESKYDATAENGINEERINGPROJECT.PUBLIC.BLUESKY_RAW_POSTS_STAGE
  SET DIRECTORY = (ENABLE = TRUE);

ALTER STAGE BLUESKYDATAENGINEERINGPROJECT.PUBLIC.BLUESKY_RAW_POSTS_STAGE REFRESH;

ALTER STAGE BLUESKYDATAENGINEERINGPROJECT.PUBLIC.BLUESKY_HYDRATED_POSTS_STAGE
  SET DIRECTORY = (ENABLE = TRUE);

ALTER STAGE BLUESKYDATAENGINEERINGPROJECT.PUBLIC.BLUESKY_HYDRATED_POSTS_STAGE REFRESH;

ALTER STAGE BLUESKYDATAENGINEERINGPROJECT.PUBLIC.BLUESKY_ACTOR_PROFILES_STAGE
  SET DIRECTORY = (ENABLE = TRUE);

ALTER STAGE BLUESKYDATAENGINEERINGPROJECT.PUBLIC.BLUESKY_ACTOR_PROFILES_STAGE REFRESH;


LIST @RAW.BLUESKY_RAW_POSTS_STAGE;
LIST @RAW.BLUESKY_ACTOR_PROFILES_STAGE;

SELECT SYSTEM$PIPE_STATUS('RAW.BLUESKY_RAW_POSTS_PIPE');




REMOVE @RAW.BLUESKY_RAW_POSTS_STAGE/demo_raw_posts.jsonl.gz;
REMOVE @RAW.BLUESKY_ACTOR_PROFILES_STAGE/demo_actor_profiles.jsonl.gz;
REMOVE @RAW.BLUESKY_RAW_POSTS_STAGE/demo/;
REMOVE @RAW.BLUESKY_ACTOR_PROFILES_STAGE/demo/;


LIST @RAW.BLUESKY_RAW_POSTS_STAGE;
LIST @RAW.BLUESKY_ACTOR_PROFILES_STAGE;


TRUNCATE TABLE RAW.LANDING_RAW_POSTS;
TRUNCATE TABLE RAW.LANDING_ACTOR_PROFILES;
TRUNCATE TABLE RAW.LANDING_TWITTER_TRENDS;
TRUNCATE TABLE RAW.LANDING_TREND_MATCHES;
TRUNCATE TABLE ENHANCED.POSTS_ENRICHED;
TRUNCATE TABLE CURATED.ML_READY;


REMOVE @RAW.BLUESKY_RAW_POSTS_STAGE/demo_run/;
REMOVE @RAW.BLUESKY_ACTOR_PROFILES_STAGE/demo_run/;
REMOVE @RAW.BLUESKY_TWITTER_TRENDS_STAGE/full/;
REMOVE @RAW.BLUESKY_TREND_MATCHES_STAGE/demo_run/;