-- Append-only streams on RAW landing tables.
-- These feed the ENHANCED layer tasks.
-- Spec: docs/SCHEMA_MIGRATION.md
-- Credit rules: docs/SNOWFLAKE_CREDIT_STRATEGY.md

CREATE STREAM IF NOT EXISTS RAW.STRM_LANDING_RAW_POSTS
  ON TABLE RAW.LANDING_RAW_POSTS
  APPEND_ONLY = TRUE
  COMMENT = 'Detects new raw posts for ENHANCED processing';

CREATE STREAM IF NOT EXISTS RAW.STRM_LANDING_HYDRATED_POSTS
  ON TABLE RAW.LANDING_HYDRATED_POSTS
  APPEND_ONLY = TRUE;

CREATE STREAM IF NOT EXISTS RAW.STRM_LANDING_ACTOR_PROFILES
  ON TABLE RAW.LANDING_ACTOR_PROFILES
  APPEND_ONLY = TRUE;

CREATE STREAM IF NOT EXISTS RAW.STRM_LANDING_TREND_MATCHES
  ON TABLE RAW.LANDING_TREND_MATCHES
  APPEND_ONLY = TRUE;
