-- Minimal bootstrap for Week 2 RAW ingestion demo environments.
-- Update these two variables only if your Snowflake target names differ.

SET TARGET_DATABASE = 'BLUESKYDATAENGINEERINGPROJECT';
SET TARGET_SCHEMA = 'PUBLIC';

CREATE DATABASE IF NOT EXISTS IDENTIFIER($TARGET_DATABASE);
USE DATABASE IDENTIFIER($TARGET_DATABASE);

CREATE SCHEMA IF NOT EXISTS IDENTIFIER($TARGET_SCHEMA);
USE SCHEMA IDENTIFIER($TARGET_SCHEMA);
