-- Snowflake loader v1 setup: one internal stage per dataset family.

CREATE STAGE IF NOT EXISTS BLUESKY_RAW_POSTS_STAGE
  FILE_FORMAT = BLUESKY_JSONL_GZ;

CREATE STAGE IF NOT EXISTS BLUESKY_HYDRATED_POSTS_STAGE
  FILE_FORMAT = BLUESKY_JSONL_GZ;

CREATE STAGE IF NOT EXISTS BLUESKY_HYDRATION_MISSES_STAGE
  FILE_FORMAT = BLUESKY_JSONL_GZ;

CREATE STAGE IF NOT EXISTS BLUESKY_ACTOR_PROFILES_STAGE
  FILE_FORMAT = BLUESKY_JSONL_GZ;
