-- One internal stage per dataset family, all in RAW schema.
-- Spec: docs/SCHEMA_MIGRATION.md
-- Credit rules: docs/SNOWFLAKE_CREDIT_STRATEGY.md

CREATE STAGE IF NOT EXISTS RAW.BLUESKY_RAW_POSTS_STAGE
  FILE_FORMAT = RAW.BLUESKY_JSONL_GZ;

CREATE STAGE IF NOT EXISTS RAW.BLUESKY_HYDRATED_POSTS_STAGE
  FILE_FORMAT = RAW.BLUESKY_JSONL_GZ;

CREATE STAGE IF NOT EXISTS RAW.BLUESKY_HYDRATION_MISSES_STAGE
  FILE_FORMAT = RAW.BLUESKY_JSONL_GZ;

CREATE STAGE IF NOT EXISTS RAW.BLUESKY_ACTOR_PROFILES_STAGE
  FILE_FORMAT = RAW.BLUESKY_JSONL_GZ;

CREATE STAGE IF NOT EXISTS RAW.BLUESKY_TWITTER_TRENDS_STAGE
  FILE_FORMAT = RAW.BLUESKY_JSONL_GZ;

CREATE STAGE IF NOT EXISTS RAW.BLUESKY_TREND_MATCHES_STAGE
  FILE_FORMAT = RAW.BLUESKY_JSONL_GZ;
