-- Initial streams scaffolding over landing append surfaces.

CREATE STREAM IF NOT EXISTS STRM_LANDING_RAW_POSTS
  ON TABLE LANDING_RAW_POSTS
  APPEND_ONLY = TRUE;

CREATE STREAM IF NOT EXISTS STRM_LANDING_HYDRATED_POSTS
  ON TABLE LANDING_HYDRATED_POSTS
  APPEND_ONLY = TRUE;

CREATE STREAM IF NOT EXISTS STRM_LANDING_HYDRATION_MISSES
  ON TABLE LANDING_HYDRATION_MISSES
  APPEND_ONLY = TRUE;

CREATE STREAM IF NOT EXISTS STRM_LANDING_ACTOR_PROFILES
  ON TABLE LANDING_ACTOR_PROFILES
  APPEND_ONLY = TRUE;
