-- Initial task scaffolding only.
-- These are intentionally suspended placeholders for v1.

CREATE TASK IF NOT EXISTS TASK_BLUESKY_STREAM_HEARTBEAT
  SCHEDULE = 'USING CRON */15 * * * * UTC'
  USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
AS
SELECT
  CURRENT_TIMESTAMP() AS checked_at,
  SYSTEM$STREAM_HAS_DATA('STRM_LANDING_RAW_POSTS') AS raw_has_data,
  SYSTEM$STREAM_HAS_DATA('STRM_LANDING_HYDRATED_POSTS') AS hydrated_has_data,
  SYSTEM$STREAM_HAS_DATA('STRM_LANDING_HYDRATION_MISSES') AS misses_has_data,
  SYSTEM$STREAM_HAS_DATA('STRM_LANDING_ACTOR_PROFILES') AS actor_has_data;

ALTER TASK TASK_BLUESKY_STREAM_HEARTBEAT SUSPEND;
