-- ════════════════════════════════════════════════════════════════════
-- WARNING: Run this script ONLY after RAW schema objects are confirmed
-- working. This drops all old PUBLIC schema objects permanently.
-- ════════════════════════════════════════════════════════════════════
-- Spec: docs/SCHEMA_MIGRATION.md (Step 8)
-- Credit rules: docs/SNOWFLAKE_CREDIT_STRATEGY.md

-- ── Drop views (reverse dependency order: curated → staging) ──
DROP VIEW IF EXISTS PUBLIC.CURATED_ML_READY;
DROP VIEW IF EXISTS PUBLIC.CURATED_POSTS_WITH_TRENDS;
DROP VIEW IF EXISTS PUBLIC.CURATED_POSTS_LABELED;
DROP VIEW IF EXISTS PUBLIC.CURATED_POSTS_CORE;
DROP VIEW IF EXISTS PUBLIC.STG_ENHANCED_ACTORS;
DROP VIEW IF EXISTS PUBLIC.STG_ENHANCED_POSTS;
DROP VIEW IF EXISTS PUBLIC.STG_TWITTER_TRENDS;
DROP VIEW IF EXISTS PUBLIC.STG_ACTOR_PROFILES;
DROP VIEW IF EXISTS PUBLIC.STG_HYDRATION_MISSES;
DROP VIEW IF EXISTS PUBLIC.STG_HYDRATED_POSTS;
DROP VIEW IF EXISTS PUBLIC.STG_RAW_POSTS;

-- ── Drop UDF ──
DROP FUNCTION IF EXISTS PUBLIC.CLEAN_PROFANITY(STRING);

-- ── Drop task ──
DROP TASK IF EXISTS PUBLIC.TASK_BLUESKY_STREAM_HEARTBEAT;

-- ── Drop streams ──
DROP STREAM IF EXISTS PUBLIC.STRM_LANDING_RAW_POSTS;
DROP STREAM IF EXISTS PUBLIC.STRM_LANDING_HYDRATED_POSTS;
DROP STREAM IF EXISTS PUBLIC.STRM_LANDING_HYDRATION_MISSES;
DROP STREAM IF EXISTS PUBLIC.STRM_LANDING_ACTOR_PROFILES;

-- ── Drop pipes ──
DROP PIPE IF EXISTS PUBLIC.BLUESKY_RAW_POSTS_PIPE;
DROP PIPE IF EXISTS PUBLIC.BLUESKY_HYDRATED_POSTS_PIPE;
DROP PIPE IF EXISTS PUBLIC.BLUESKY_HYDRATION_MISSES_PIPE;
DROP PIPE IF EXISTS PUBLIC.BLUESKY_ACTOR_PROFILES_PIPE;

-- ── Drop stages ──
DROP STAGE IF EXISTS PUBLIC.BLUESKY_RAW_POSTS_STAGE;
DROP STAGE IF EXISTS PUBLIC.BLUESKY_HYDRATED_POSTS_STAGE;
DROP STAGE IF EXISTS PUBLIC.BLUESKY_HYDRATION_MISSES_STAGE;
DROP STAGE IF EXISTS PUBLIC.BLUESKY_ACTOR_PROFILES_STAGE;
DROP STAGE IF EXISTS PUBLIC.BLUESKY_TWITTER_TRENDS_STAGE;

-- ── Drop file format ──
DROP FILE FORMAT IF EXISTS PUBLIC.BLUESKY_JSONL_GZ;

-- Reminder: suspend warehouse after running cleanup.
-- ALTER WAREHOUSE COMPUTE_WH SUSPEND;


SELECT TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'PUBLIC'
ORDER BY TABLE_TYPE, TABLE_NAME;