-- Zero-copy migration: move landing tables from PUBLIC to RAW schema.
-- ALTER TABLE RENAME is metadata-only — no data is copied or moved.
-- Spec: docs/SCHEMA_MIGRATION.md (Step 2)
-- Credit rules: docs/SNOWFLAKE_CREDIT_STRATEGY.md
--
-- EXECUTION ORDER: Run this BEFORE 00_drop_public_objects.sql
-- and BEFORE 02_pipes.sql (pipes reference RAW.LANDING_* tables).

ALTER TABLE PUBLIC.LANDING_RAW_POSTS       RENAME TO RAW.LANDING_RAW_POSTS;
ALTER TABLE PUBLIC.LANDING_HYDRATED_POSTS   RENAME TO RAW.LANDING_HYDRATED_POSTS;
ALTER TABLE PUBLIC.LANDING_HYDRATION_MISSES RENAME TO RAW.LANDING_HYDRATION_MISSES;
ALTER TABLE PUBLIC.LANDING_ACTOR_PROFILES   RENAME TO RAW.LANDING_ACTOR_PROFILES;
ALTER TABLE PUBLIC.LANDING_TWITTER_TRENDS   RENAME TO RAW.LANDING_TWITTER_TRENDS;
--ALTER TABLE PUBLIC.LOADER_FILE_MANIFEST     RENAME TO RAW.LOADER_FILE_MANIFEST;
